# Uncomment the next line to define a global platform for your project
platform :ios, '10'

target 'test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "RecastAI" , ">3.0.0"
  pod "ForecastIO"
  pod "JSQMessagesViewController" 
  # Pods for test

end
